name: 'AWS CLI Action'
description: 'Custom GitHub Action for AWS CLI operations'
inputs:
  args:
    description: 'Arguments to pass to the AWS CLI command'
    required: true
runs:
  using: 'docker'
  image: 'ubuntu:latest'
  steps:
    - name: Install AWS CLI
      run: |
        apt-get update
        apt-get install -y unzip
        curl "https://d1uj6qtbmh3dt5.cloudfront.net/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install
    - name: Run AWS CLI Command
      run: aws ${{ inputs.args }}
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
