### Variables
@baseUrl = http://localhost:8080/api/books
@contentType = application/json

### Get all Books
GET {{baseUrl}}

### Get Book by ID
GET {{baseUrl}}/9

### Create new Book (ML Service Test)
POST {{baseUrl}}/generate_fairytale/3
Content-Type: application/json

{
  "name": "지수",
  "age": 3,
  "gender": "female",
  "emotion": "즐거움과 신남",
  "health": "활기차고 건강함",
  "nutrition": "식사에 대한 정보는 제공되지 않음",
  "activities": "아이스크림 가게 역할놀이, 놀이터에서 놀기, 붓으로 그림 그리기",
  "social": "친구들과 함께 즐겁게 놀며 웃음소리를 나누었음",
  "special": "아이스크림 가게 역할을 진지하게 맡아 연기함",
  "keywords": "아이스크림,역할놀이,놀이터,그림,웃음,잠자리",
  "diary": "오늘은 정말 신나는 하루였어! 😄  \n아침에 일어나서 기분이 너무 좋았어. ☀️  \n나는 친구들과 함께 아이스크림 가게 역할놀이를 했어. 🍦  \n내가 아이스크림 가게 주인 역할을 맡았는데, 진짜로 가게를 운영하는 것처럼 연기했어! 🎭  \n친구들이 와서 다양한 맛의 아이스크림을 주문했어.  \n우리는 서로 웃으면서 즐거운 시간을 보냈어! 😂  \n\n그 다음에는 놀이터로 갔어. 🛝  \n미끄럼틀도 타고, 그네도 타고, 정말 신났어!  \n친구들과 함께 뛰어놀면서 웃음소리가 끊이지 않았어. 🎉  \n놀이터에서의 시간은 항상 너무 재밌어!  \n\n마지막으로 붓으로 그림을 그렸어. 🎨  \n색깔이 너무 예쁘고, 내 그림이 멋지게 나왔어!  \n오늘 하루는 정말 즐거웠고, 나는 건강하고 활기차! 💪  \n내일도 이렇게 신나는 하루가 되길 바래! 🌈",
  "user_id": 1,
  "baby_id": 1
}

### Update Book
PUT {{baseUrl}}/11
Content-Type: {{contentType}}

{
  "userId": 1,
  "title": "바밤바의 신나는 모험",
  "coverPath": "/covers/babamba_updated.png",
  "startDate": "2024-03-01T00:00:00",
  "endDate": "2024-03-07T23:59:59",
  "generatedDate": "2024-03-01T09:00:00"
}

### Delete Book
DELETE {{baseUrl}}/8