### Variables
@baseUrl = http://localhost:8080/api/books
@contentType = application/json

### Get all Books
GET {{baseUrl}}

### Get Book by ID
GET {{baseUrl}}/1

### Create new Book
POST {{baseUrl}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="book"
Content-Type: application/json

{
  "userId": 1,
  "title": "바밤바의 모험",
  "startDate": "2024-03-01T00:00:00",
  "endDate": "2024-03-07T23:59:59",
  "generatedDate": "2024-03-01T09:00:00"
}
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="coverImage"; filename="바밤바.png"
Content-Type: image/png

< C:/hyun98/바밤바.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### Update Book
PUT {{baseUrl}}/11
Content-Type: {{contentType}}

{
  "userId": 1,
  "title": "바밤바의 신나는 모험",
  "coverPath": "/covers/babamba_updated.png",
  "startDate": "2024-03-01T00:00:00",
  "endDate": "2024-03-07T23:59:59",
  "generatedDate": "2024-03-01T09:00:00"
}

### Delete Book
DELETE {{baseUrl}}/8