### Variables
@baseUrl = http://localhost:8080/api/fairy-tale
@contentType = application/json

### Get all FairyTales
GET {{baseUrl}}

### Get FairyTale by ID
GET {{baseUrl}}/1

### Create new FairyTale
POST {{baseUrl}}
Content-Type: {{contentType}}

{
  "userId": 1,
  "content": "옛날 옛적에 작은 토끼가 살았습니다...",
  "startDate": "2024-03-01T00:00:00",
  "endDate": "2024-03-07T23:59:59",
  "generatedDate": "2024-03-01T09:00:00"
}

### Update FairyTale
PUT {{baseUrl}}/1
Content-Type: {{contentType}}

{
  "userId": 1,
  "content": "옛날 옛적에 작고 귀여운 토끼가 살았습니다...",
  "startDate": "2024-03-01T00:00:00",
  "endDate": "2024-03-07T23:59:59",
  "generatedDate": "2024-03-01T09:00:00"
}

### Delete FairyTale
DELETE {{baseUrl}}/1