### gethello
GET http://localhost:8080/api/events

### create event
POST http://localhost:8080/api/events
Content-Type: application/json

{
  "eventPhotoId": null,
  "userId": 2,
  "fairyTaleId": 1,
  "title": "Wdi",
  "description": "Alice and Bob's 5th ",
  "startTime": "2024-09-15T19:00:00",
  "endTime": "2024-09-15T23:00:00",
  "location": "Alice's House"
}

###get event(time)
GET http://localhost:8080/api/events/between?start=2024-09-15T19:00:00&end=2024-09-15T23:00:00

### get event
GET http://localhost:8080/api/events/1

###UPDATE EVENT
PUT http://localhost:8080/api/events/1
Content-Type: application/json

{
  "eventPhotoId": null,
  "userId": 2,
  "fairyTaleId": 1,
  "title": "Wdddfdfi",
  "description": "Alice and Bob's 5th ",
  "startTime": "2024-09-15T19:00:00",
  "endTime": "2024-09-15T23:00:00",
  "location": "Alice's House"
}

###delete event
DELETE http://localhost:8080/api/events/3

###get memo
GET http://localhost:8080/api/memos

###put memo
POST http://localhost:8080/api/memos/10
Content-Type: application/json

{
  "userId": 1,
  "diaryId": 1,
  "fairyTaleId": 1,
  "createdAt": "2024-09-15T19:00:00",
  "content": "수정당sdfs."
}

###delete memo
DELETE http://localhost:8080/api/memos/1

###get memo by id
GET http://localhost:8080/api/memos/2

###get alim
GET http://localhost:8080/api/alims